#!/usr/bin/env sh
# Install git-recap: downloads the latest prebuilt release binary for your
# platform (checksum-verified). No Go toolchain needed.
#
#   curl -fsSL https://raw.githubusercontent.com/salvodicara/git-recap/main/install.sh | sh
#
# Override the destination with PREFIX, e.g. PREFIX=/usr/local/bin
#
# Uninstall (removes everything this script creates):
#   rm -f ~/.local/bin/git-recap ~/.config/fish/completions/git-recap.fish
set -eu

REPO="salvodicara/git-recap"
PREFIX="${PREFIX:-$HOME/.local/bin}"

for c in curl tar; do
  command -v "$c" >/dev/null 2>&1 || { echo "error: $c is required" >&2; exit 1; }
done

os=$(uname -s | tr '[:upper:]' '[:lower:]')
arch=$(uname -m)
case "$arch" in
  x86_64) arch=amd64 ;;
  aarch64 | arm64) arch=arm64 ;;
  *) echo "error: unsupported architecture $arch — try: go install github.com/$REPO@latest" >&2; exit 1 ;;
esac
case "$os" in
  darwin | linux) ;;
  *) echo "error: unsupported OS $os — Windows zips: https://github.com/$REPO/releases" >&2; exit 1 ;;
esac

asset="git-recap_${os}_${arch}.tar.gz"
base="https://github.com/$REPO/releases/latest/download"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

echo "Downloading $asset..."
curl -fsSL "$base/$asset" -o "$tmp/$asset"
curl -fsSL "$base/checksums.txt" -o "$tmp/checksums.txt"

if command -v shasum >/dev/null 2>&1; then
  sum() { shasum -a 256 -c -; }
else
  sum() { sha256sum -c -; }
fi
(cd "$tmp" && grep " $asset\$" checksums.txt | sum >/dev/null) || {
  echo "error: checksum verification failed" >&2
  exit 1
}

tar -xzf "$tmp/$asset" -C "$tmp" git-recap
mkdir -p "$PREFIX"
mv "$tmp/git-recap" "$PREFIX/git-recap"
echo "Installed $PREFIX/git-recap ($("$PREFIX/git-recap" version))"

# Completions: fish auto-loads from its user dir, so install those directly —
# but never clobber a file we didn't generate, and never leave a stray one
# behind if the binary predates the completion subcommand.
# bash/zsh rc files are yours — we only print the line to add.
if command -v fish >/dev/null 2>&1; then
  fish_file="$HOME/.config/fish/completions/git-recap.fish"
  # Ours = missing, empty, or carrying a header we've ever generated;
  # a user's hand-written file is left alone. Write via temp so an existing
  # file is never truncated if the binary predates `completion`.
  if [ ! -e "$fish_file" ] || [ ! -s "$fish_file" ] ||
     head -1 "$fish_file" | grep -qE "generated by git-recap|fish completion for git-recap"; then
    if "$PREFIX/git-recap" completion fish > "$tmp/git-recap.fish" 2>/dev/null; then
      mkdir -p "${fish_file%/*}"
      mv "$tmp/git-recap.fish" "$fish_file"
      echo "Installed fish completions."
    fi
  fi
fi
echo "Completions (bash/zsh): add to your shell rc — see \`git-recap completion\` or the README."

case ":$PATH:" in
  *":$PREFIX:"*) ;;
  *) echo "note: $PREFIX is not on your PATH — add it to use \`git-recap\` / \`git recap\`." ;;
esac
